version: "3.7"
services:
  app:
    image: kooldev/php:7.4-nginx
    ports:
    - ${KOOL_APP_PORT:-80}:80
    environment:
      ASUSER: ${KOOL_ASUSER:-0}
      UID: ${UID:-0}
      NGINX_FASTCGI_READ_TIMEOUT: 180s
      PHP_MAX_EXECUTION_TIME: 180
    volumes:
    - .:/app:delegated
    - /vendor
    - /node_modules
    networks:
    - kool_local
    - kool_global
  database:
    image: mysql:5.7
    ports:
    - ${KOOL_DATABASE_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD-rootpass}
      MYSQL_DATABASE: ${DB_DATABASE-database}
      MYSQL_USER: ${DB_USERNAME-user}
      MYSQL_PASSWORD: ${DB_PASSWORD-pass}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
    - database:/var/lib/mysql:delegated
    networks:
    - kool_local
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - mysqladmin
      - ping
  phpmyadmin:
      depends_on:
          - database
      image: phpmyadmin/phpmyadmin
      environment:
          PMA_HOST: database
      restart: unless-stopped
      ports:
          - 8081:80
      networks:
          - kool_local
  cache:
    image: redis:6-alpine
    volumes:
    - cache:/data:delegated
    networks:
    - kool_local
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
    restart: unless-stopped
volumes:
  database: null
  cache: null
networks:
  kool_local: null
  kool_global:
    external: true
    name: ${KOOL_GLOBAL_NETWORK:-kool_global}
